server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
    open-in-view: false
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    org.springframework.security: INFO
    com.sinoe.authmfa: DEBUG

app:
  jwt:
    secret: ${JWT_SECRET}
    exp-minutes: ${JWT_EXP_MINUTES:60}
  otp:
    exp-minutes: ${OTP_EXP_MINUTES:5}
    max-attempts: ${OTP_MAX_ATTEMPTS:5}
    resend-cooldown-seconds: ${OTP_RESEND_COOLDOWN_SECONDS:60}
